//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
        }
    
        public int doctor_id { get; set; }
        public string name { get; set; }
        public string information { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public int experience { get; set; }
        public int patients_count { get; set; }
        public int cabinet_number { get; set; }
        public Nullable<double> rating { get; set; }
        public int department_id { get; set; }
        public int account_id { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
